menu_items:
  - location: application
    label:
      en: Memos
      zh: 备忘录
    url: "apps/memos?theme={system_theme}"
    url_type: iframe

require_version:
 version: "> 1.1.66"
 reason:
     en: "Requires new API features"
     zh: "需要新的API功能"